name: feast-trino
type: python


env:
  CFLAGS: "-I$(brew --prefix xz)/include" # Fix for m1 macs. Does not work on intel
  LDFLAGS: "-L$(brew --prefix xz)/lib" # Fix for m1 macs. Does not work on intel
  GRPC_PYTHON_BUILD_SYSTEM_OPENSSL: "1"  # Fix grpc install on m1 macs
  GRPC_PYTHON_BUILD_SYSTEM_ZLIB: "1"  # Fix grpc install on m1 macs

up:
  - homebrew:
    - xz
    - protobuf
    - openssl
    - zlib
  - python: 3.9.8
  - custom:
      name: Install the dependencies locally
      met?: make install-ci-dependencies
      meet: "True"
  - custom:
     name: Reinstall protobuf with M1 compatibility
     met?: |
      pip install protobuf==3.17 --force-reinstall --no-deps --install-option="--cpp_implementation"
     meet: "true"