
.PHONY: build

ROOT_DIR 	:= $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

format:
	# Sort
	cd ${ROOT_DIR}; isort feast_trino/

	# Format
	cd ${ROOT_DIR}; black --target-version py37 feast_trino tests

lint:
	cd ${ROOT_DIR}; mypy feast_trino/ tests/
	cd ${ROOT_DIR}; isort feast_trino/ tests/ --check-only
	cd ${ROOT_DIR}; flake8 feast_trino/ tests/
	cd ${ROOT_DIR}; black --check feast_trino tests

build:
	rm -rf dist/*
	python setup.py sdist bdist_wheel