
.PHONY: build

ROOT_DIR 	:= $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

format:
	# Sort
	cd ${ROOT_DIR}; python -m isort feast_trino/

	# Format
	cd ${ROOT_DIR}; python -m black --target-version py37 feast_trino

lint:
	cd ${ROOT_DIR}; python -m mypy feast_trino/
	cd ${ROOT_DIR}; python -m isort feast_trino/ --check-only
	cd ${ROOT_DIR}; python -m flake8 feast_trino/
	cd ${ROOT_DIR}; python -m black --check feast_trino 

build:
	rm -rf dist/*
	python setup.py sdist bdist_wheel